### ISSUE TITLE
Page blanche exercice P1C3

### ISSUE THREAD

**Issue by naiiipan44** [OpenClassrooms-Student-Center/1603881-creez-votre-site-web-avec-html5-et-css3#79]
Pour réaliser le 1er exercice du cours j'ai fait copié collé la structure de code dans visual code et ajouté " Robbie Lens - Photographie  entre les balises title. Seulement lorsque je clique sur mon fichier htlm pour qu'il s'affiche dans mon navigateur une page blanche s'ouvre. 
Help me please ! 
Thank you

**Comment by Y-ann-B** [comment]
> Pour réaliser le 1er exercice du cours j'ai fait copié collé la structure de code dans visual code et ajouté " Robbie Lens - Photographie entre les balises title. Seulement lorsque je clique sur mon fichier htlm pour qu'il s'affiche dans mon navigateur une page blanche s'ouvre. Help me please ! Thank you
 
Bonjour 
la balise title n'affiche que dans l'onglet du navigateur 
vous devez taper un texte dans le corps (intérieure des balises <body></body>) avec une balise paragraphe pour qu'il y est quelque chose sur la page en elle même

**Comment by naiiipan44** [comment]
Bonjour,

Merci ! J'ai oublié de vous répondre
